- tap:
  - caskroom/cask
  - caskroom/fonts
  - homebrew/core

- cask:
  - docker
  - flash-player
  - google-chrome
  - hammerspoon
  - handbrake
  - imagealpha
  - imageoptim
  - java
  - latexit
  - mactex
  - miniconda
  - ngrok
  - numi
  - osxfuse
  - qlcolorcode
  - qlimagesize
  - qlmarkdown
  - qlprettypatch
  - qlstephen
  - quicklook-csv
  - quicklook-json
  - skim
  - skype
  - transmission
  - typora
  - vagrant
  - vagrant-manager
  - virtualbox
  - visual-studio-code
  - vlc
  - webpquicklook

- brew:
  - aspcud
  - aspell
  - autoconf
  - automake
  - bash-completion
  - cairo
  - cmake
  - ffmpeg
  - fontconfig
  - freetype
  - fzf
  - gcc
  - gcc@6
  - gd
  - gdbm
  - gettext
  - ghostscript
  - git
  - glib
  - gmp
  - grip
  - hdf5
  - htop
  - hub
  - hunspell
  - icu4c
  - isl
  - jemalloc
  - jpeg
  - lame
  - lapack
  - libevent
  - libffi
  - libidn2
  - libmpc
  - libpng
  - libtermkey
  - libtiff
  - libtool
  - libunistring
  - libuv
  - libvterm
  - libyaml
  - libzip
  - little-cms2
  - llvm
  - lua
  - luajit
  - mpfr
  - msgpack
  - neovim
  - nmap
  - node
  - ocaml
  - ocamlbuild
  - opam
  - open-mpi
  - openssl
  - pcre
  - perl
  - pixman
  - pkg-config
  - pv
  - python
  - ruby
  - rbenv
  - ruby-build
  - readline
  - shellcheck
  - sqlite
  - ssh-copy-id
  - sshfs
  - swig
  - szip
  - the_silver_searcher
  - tldr
  - tmux
  - tree
  - unibilium
  - universal-ctags
  - vim
  - webp
  - wget
  - x264
  - xvid
  - xz
  - zsh
  - zsh-completions
  - zsh-git-prompt

