- link:
    ~/.vimrc:                editors/vim/vimrc
    ~/.vim:                  editors/vim
    ~/.config/nvim:          editors/vim
    ~/.config/nvim/init.vim: editors/vim/vimrc

# check for later to install the plugins
- shell:
    # needs to surpress exit status
    # -> due to wrong interpretation of fzf exit
    - ["vim -c 'PlugInstall!' +qall; exit 0", 'Install vim plugins']
