- defaults:
    link:
      create: true
      relink: true

- clean: [
    '~',
    '~/.config'
]

- link:
    ~/.dotfiles: ''

- shell:
    - ["git submodule update --recursive --remote", "Update gitbot"]
